on: [push]

#Perform Scanning on Website when new configuration pushed to GitHub

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
#Automate Security Testing with ZAP and GitHub Actions
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://hpdm-bmi-app.herokuapp.com/'
          cmd_options: '-a'
#Dynamic Application Security Testing with ZAP and GitHub Actions
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://hpdm-bmi-app.herokuapp.com/api?height=167&weight=70'
          cmd_options: '-a'